### ISSUE TITLE
Test Notifications

### ISSUE THREAD

**Issue by lionslair** [bljohnsondev/mishos#6]
Is there a way to test notifications once you have entered a apprise url?

**Comment by bljohnsondev** [comment]
There isn't currently but this is a great idea.  I'll add an item to my todo list to add a "Test Notification" button on the settings page.  For now you can test it via curl.  If you are using tags (which is how I'm using Apprise) you can test your endpoint like this:

```sh
curl -X POST -d '{"subject": "test title", "body":"test message"}' -H "Content-Type: application/json" http://localhost:8000/notify/abc123
```

Change the URL to your Apprise endpoint (assuming abc123 is the tag to your preferred notification service) and you should be good.  You can see the docs [here](https://github.com/caronc/apprise-api?tab=readme-ov-file#persistent-stateful-storage-solution).

**Comment by lionslair** [comment]
So in the readme it appears that the app  calls the notification an hour out from being played. 

It seems just the endpoint is called. So you have an apprise config for each tv show configured? Haven't tried digging into the code to look but just the endpoint is called no payload is passed to apprise with the the show, body, image url or anything correct?

**Comment by bljohnsondev** [comment]
It calls your configured endpoint an hour before a show airs.  It passes a payload with the show name as the title and the episode number and episode title in the body.  At the end of the readme there is a Gotify screenshot that shows an example of the message.  It uses the same endpoint call for all show notifications.

I will put a note to expand a bit in the readme about the payload and provide a bit more details.  Hope this helps.

**Comment by lionslair** [comment]
Thanks

**Comment by bljohnsondev** [comment]
I've added a "Send Test" button next to the notification URL on the settings screen.  This will allow you to test the URL you've entered in the notification URL input.  The backend system will try and send a test TV show notification to the provided URL.

Hope this helps!
